/**
 * Canlı veritabanındaki BÜTÜN soru ve gelişim başlıkları (8 Ağustos 2026).
 *
 * Etiket eşlemesi uydurma metinlerle değil gerçek verilerle sınanır:
 * kurum yeni bir atölye eklediğinde başlıklar değişiyor ve eşleme
 * sessizce kör kalabiliyor.
 */
export const GERCEK_BASLIKLAR: readonly string[] = [
  "Aktif Katılım",
  "Aktif Katılım ve Araştırma İsteği",
  "Algoritmik Düşünme Becerisi",
  "Analiz ve Değerlendirme",
  "Astronomik Araçlara İlgi",
  "Bağımsızlık",
  "Baş Etme Stratejileri",
  "Başkalarını Anlama ve Dinleme İsteği",
  "Bellek ve Hatırlama",
  "Bilimsel Düşünme Becerisi",
  "Bilimsel Süreçlere İlgi",
  "Bilimsel Süreçleri Kullanma",
  "Bilimsel Yöntemi Kullanma",
  "Deneylere ve Aktivitelere Katılım",
  "Detaylara Dikkat Etme",
  "Dikkat ve Konsantrasyon",
  "Dikkat ve Odaklanma Becerisi",
  "Dil Gelişimi ve Anlama",
  "Duygu Düzenleme",
  "Duygu Tanıma ve İfade Etme",
  "Duygusal Farkındalık",
  "Empati Gelişimi",
  "Empati Geliştirmeye Yönelik İlgi",
  "Empati Kurma Yeteneği",
  "Esnek Düşünme",
  "Estetik Anlayış ve Tasarım Becerisi",
  "Evren ve Gezegenlere İlgi",
  "Farklı Çözümler Arama",
  "Grup Çalışması ve Paylaşma",
  "Grup Çalışmasına Katılım",
  "Gözlem Becerileri",
  "Gözlem ve Analiz Yeteneği",
  "Hayal Gücünü Kullanma İsteği",
  "Hayal ile Gerçek Dünya Arasında Bağlantı Kurma",
  "Karar Verme Becerisi",
  "Kavramları Anlama",
  "Kendini İfade Etme İsteği",
  "Kodlama ve Programlama Yeteneği",
  "Kritik Düşünme Becerisi",
  "Kurallara Uyum",
  "Mantıksal Akıl Yürütme",
  "Mantıksal Düşünme",
  "Mekanik ve Tasarım Becerisi",
  "Olumlu Öz Algı",
  "Planetaryum Gözlemlerine İlgi",
  "Planlama ve Organizasyon",
  "Problem Çözme Becerileri",
  "Problem Çözme Becerisi",
  "Problem Çözme ve Deneme Becerisi",
  "Problem Çözme ve Hipotez Kurma",
  "Problem Çözme ve Teknik Sorunlara Müdahale",
  "Problem Çözme ve Uzlaşma",
  "Problemlere İlgi Gösterme",
  "Proje ve Görevlere Katılım",
  "Robotik Problemlerle İlgilenme",
  "Soru Sorma ve Araştırma İsteği",
  "Soru Sorma ve Fikir Geliştirme İsteği",
  "Soru Sorma ve Keşfetme İsteği",
  "Soru Sorma ve Strateji Geliştirme İsteği",
  "Sorular Sorma ve Keşfetme İsteği",
  "Sorumluluk Alma ve Yardımlaşma",
  "Sosyal Etkileşimlere Katılma",
  "Sosyal İnisiyatif",
  "Stratejik Düşünme",
  "Süreç Takibi ve Organizasyon",
  "Takım Çalışması ve İş Birliği",
  "Temel Astronomi Bilgisi",
  "Yeni Bilgilere Açıklık",
  "Yeni Bilgiye Açıklık",
  "Yeni Kavramları Öğrenmeye İstekli Olma",
  "Yeni Teknolojilere Karşı İlgi",
  "Zeka Oyunlarına İlgi",
  "Zihinsel Esneklik",
  "Zor Durumlarla Baş Etme Becerisi",
  "Zorlayıcı Görevlere İlgi",
  "Öz Yeterlilik",
  "Üretici Düşünme Becerisi",
  "Üretici Fikirlere Açıklık",
  "Üreticilik ve Yenilikçilik",
  "Üreticilik ve İnovasyon",
  "İletişim Becerileri",
  "İletişim ve İfade Becerisi",
  "İş Birliği ve Paylaşma",
];
